### ISSUE TITLE
Setup CNAME

### ISSUE THREAD

**Issue by chamkank** [nwhacks/nwhacks2019#78]
1. Port [nwhacks2018_static](https://github.com/nwhacks/nwhacks2018_static) to [2018.nwhacks.io](https://2018.nwhacks.io)
2. ~~Setup CNAME in nwhacks2019 `/build` directory ([nwhacks.io](https://nwhacks.io)). Add compile to `/docs` command in Makefile and~~ configure CNAME for `/docs` directory ([nwhacks.io](https://nwhacks.io)).

**Comment by bobheadxi** [comment]
Correction: it should probably be `/docs` directory

**Comment by bobheadxi** [comment]
> Add compile to /docs command in Makefile

heads up that the [default build script already compiles to `/docs`](https://github.com/nwhacks/nwhacks2019/blob/master/Makefile#L46)
