### ISSUE TITLE
Layout responsiveness issue - text is not centered

### ISSUE THREAD

**Issue by sherryyx** [nwhacks/nwhacks2019#92]
I know there was a bug logged previously about the text and the illustrations not being side by side on macbook pros. Now there's another bug where when the illustration appears below the text, there's a margin-right on the text that's making it horizontally off-centered.

![image](https://user-images.githubusercontent.com/29152180/45009345-84b58080-afbc-11e8-83a2-52cb73582b80.png)

**Comment by bobheadxi** [comment]
This should probably be tackled as part of #76 - I'll copy this ticket over to that one. Thanks for catching this @sherryyx !
